import { BillMaster } from 'src/app/tabs/shared/models/bill-master.model';
import { ContractTransaction } from '../contract-create-update/contract-transaction';
import { OwnerBillGroup } from '../../../shared/models/owner-bill-group';

export class Contract {
  id: number;
  clientId: number;
  contractNumber: string;
  contractDate: string;
  contractDateLocal?: string;
  tenantId: number;
  tenantName: string;
  unitId: number;
  unitNumber: string;
  utilityTypeId: number;
  utilityType: string;
  contractTypeId: number;
  contractType: string;
  // billFormatId: number;
  // billFormat: string;
  // billFormulaId: number;
  // billFormula: string;
  contractEndDate: string;
  contractEndDateLocal?: string;
  contractSuspendDate?: string;
  contractSuspendDateLocal?: string;
  reasonForContractEnd: string;
  reasonForContractSuspend: string;
  accountNumber: string;
  securityDeposit: number;
  securityDepositLocal?: string;
  remainingAmount?: number;
  remainingAmountLocal?: string;
  receivedAmount?: number;
  receivedAmountLocal?: string;
  refundAmount?: number;
  refundAmountLocal?: string;
  securityDepositInHand?: number;
  securityDepositInHandLocal?: string;
  isSecurityDepositPaid: boolean;
  status: string;
  isAssignToOwner: boolean;
  billMasters?: BillMaster[];
  isGroupBill?: boolean;
  ownerBillGroups?: OwnerBillGroup[];
  type?: string;
  isSuspended?: boolean;
  isDeleted?: boolean;
  previousDueAmount?: number;
  contractReActivatedDate?: string;
  contractTransactions?: ContractTransaction[]
  mode: 'create' | 'update' | 'renew' | 'delete';
  checkDues?: boolean;
  constructor(contract) {
    this.id = contract.id || 0;
    this.clientId = contract.clientId || 0;
    this.contractNumber = contract.contractNumber || '';
    this.contractDate = contract.contractDate || '';
    this.tenantId = contract.tenantId || 0;
    this.tenantName = contract.tenantName || '';
    this.unitId = contract.unitId || 0;
    this.unitNumber = contract.unitNumber || '';
    this.utilityTypeId = contract.utilityTypeId || 0;
    this.utilityType = contract.utilityType || '';
    this.contractTypeId = contract.contractTypeId || 0;
    this.contractType = contract.contractType || '';
    // this.billFormatId = contract.billFormatId || 0;
    // this.billFormat = contract.billFormat || '';
    // this.billFormulaId = contract.billFormulaId || 0;
    // this.billFormula = contract.billFormula || '';
    this.contractEndDate = contract.contractEndDate || null;
    this.contractSuspendDate = contract.contractSuspendDate || null;
    this.reasonForContractEnd = contract.reasonForContractEnd || '';
    this.accountNumber = contract.accountNumber || '';
    //this.isDeleted = contract.isDeleted || false;
    this.type = contract.type || '';
    this.mode = contract.mode || 'create';
    this.securityDeposit = contract.securityDeposit || 0;
    this.receivedAmount = contract.receivedAmount || 0;
    this.remainingAmount = contract.remainingAmount || 0;
    this.refundAmount = contract.refundAmount || 0;
    this.previousDueAmount = contract.previousDueAmount || 0;
    this.isSecurityDepositPaid = contract.isSecurityDepositPaid || false;
    this.isGroupBill = contract.isGroupBill || false;
    this.status = contract.status || '';
    this.isSuspended = contract.isSuspended || false;
    this.isAssignToOwner = contract.isAssignToOwner || false;
    this.isDeleted = contract.isDeleted || false;
    this.contractReActivatedDate = contract.contractReActivatedDate || null;
    this.billMasters = (contract.billMasters || []);
    this.ownerBillGroups = (contract.ownerBillGroups || []).map(ownerBillGroup => new OwnerBillGroup(ownerBillGroup));
    this.contractTransactions = (contract.contractTransactions || []);
    this.checkDues = true;
  }
}